plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.mehmetemreak.stickhome'
    compileSdk 34

    defaultConfig {
        applicationId "io.github.mehmetemreak.stickhome"
        minSdk 29
        targetSdk 29
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
